# Generated by Django 6.1.1 on 2026-09-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='GovtID_type',
            new_name='GovtID_Type',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='id_Number',
            new_name='ID_Number',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='Reviewer_comment',
            new_name='Reviewer_Comments',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='Reviewer_id',
            new_name='Reviewer_ID',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='Status_name',
            new_name='Status_Name',
        ),
    ]
