# Generated by Django 6.1.1 on 2026-09-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_gender_applicant_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='Load_applied',
            new_name='Load_Applied',
        ),
    ]
